version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - 6380:6379
    volumes:
      - redis:/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: movie-db

volumes:
  redis:
    driver: local
